version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: schematest5_14am
  MYSQL_USER: root
  MYSQL_PASSWORD: IsraI@9312

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    networks:
      - napp
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: IsraI@9312
      MYSQL_HOST: localhost
      MYSQL_DATABASE: schematest5_14am
  
  client:
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    networks:
      - napp
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    networks:
      - napp
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
       <<: *common-variables
       MYSQL_HOST_IP: mysql_db


  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      networks:
        - napp
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
networks:
  napp:
    driver: bridge